package com.rcm.ssh.storemanager.domain;
// Generated 2017-2-18 12:40:09 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.struts2.json.annotations.JSON;
import org.hibernate.annotations.GenericGenerator;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "stores", catalog = "ssh_store")
public class Store implements java.io.Serializable {

	private String id;
	private String name;
	private String addr;
	private String manager;
	private Set<Good> goods = new HashSet<Good>(0);

	public Store() {
	}

	public Store(String name, String addr, String manager, Set<Good> goods) {
		this.name = name;
		this.addr = addr;
		this.manager = manager;
		this.goods = goods;
	}

	@GenericGenerator(name = "generator", strategy = "uuid")
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false, length = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "addr", length = 100)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "manager", length = 32)
	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "store")
	@JSON(serialize = false) //解决懒加载的方法
	public Set<Good> getGoods() {
		return this.goods;
	}

	public void setGoods(Set<Good> goods) {
		this.goods = goods;
	}

}
